version: 2.1

# Define the jobs we want to run for this project
jobs:
  dev:
    docker:
      - image: cimg/openjdk:11.0.13
        auth:
          username: lkjoshi
          password: $L2k8j72 # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the build job"
  QA:
    docker:
      - image: cimg/openjdk:11.0.13
        auth:
          username: lkjoshi
          password: $L2k8j72 # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: cimg/openjdk:11.0.13
        auth:
          username: lkjoshi
          password: $L2k8j72  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the test job"
      
      # Orchestrate our job run sequence


workflows2:
  dev_and_QA:
    jobs:
      - dev
      - QA
        requires:
          -dev
